#!/bin/zsh

echo "To use this tool you must provide a password: "
read -r pass

if [[ "$pass" =~ ^([Uu][wW][uU]|[1][3][2][4])$ ]]
then
	echo -n
else
	echo -n "Literally nice try, relaunch the tool and try the CORRECT password 🙄 "; echo
	exit
fi

echo "Which location is the password file?"
read -r l


l=$(echo "${l/\~//Users/736590}")

if [ -f $l ]
then
	echo -n
else
	echo -n "File doesn't exist."
	exit
fi


cat $l | grep hexa >/dev/null; RET=$?

if [[ $RET -eq 0 ]]
then
	pop=$(mktemp)
	xxd -r $l > $pop
	try=$(cat $pop | wc -c)
	let x="try / 2 + 150000"
	try2=$(cat $pop | head -c $x | tail -c 150000)
	try3=$(echo $try2 | sed -r 's/\x1B\[([0-9;]+)[mK]//g' | sed 's/password//gI' | awk '{print $2}')
	echo $try3
	rm -f $pop
else
	try=$(cat $l | wc -c)
	let x="try / 2 + 150000"
	try2=$(cat $l | head -c $x | tail -c 150000)
	try3=$(echo $try2 | sed -r 's/\x1B\[([0-9;]+)[mK]//g' | sed 's/password//gI' | awk '{print $2}')
	echo $try3
fi

#echo $(echo $try2 | sed -r 's/\x1B\[([0-9;]+)[mK]//g' | sed 's/password//gI' | grep -vi "salt\|hex")